{"result":{"history_size":3,"folders":["pa1"],"nr":199,"data":{"embed_links":[]},"created":"2024-10-19T21:27:03Z","bucket_order":3,"no_answer_followup":1,"change_log":[{"anon":"stud","data":"m2go5zbiiot7fy","v":"private","type":"create","when":"2024-10-19T21:27:03Z","uid_a":"a_0"},{"anon":"no","uid":"ln0md59uz9w3kd","data":"m2gqcwdoq451l9","to":"m2go5zb93dh7fx","type":"i_answer","when":"2024-10-19T22:28:25Z"},{"anon":"no","uid":"ln0md59uz9w3kd","to":"m2go5zb93dh7fx","type":"followup","when":"2024-10-19T22:28:50Z","cid":"m2gqdfsmeup2ch"},{"anon":"stud","data":"m2gqfllrlnx5ij","v":"private","type":"update","when":"2024-10-19T22:30:31Z","uid_a":"a_0"},{"anon":"stud","to":"m2go5zb93dh7fx","type":"feedback","when":"2024-10-19T22:31:34Z","cid":"m2gqgy1on567di","uid_a":"a_0"},{"anon":"stud","data":"m2gqha3hq1b55","v":"all","type":"update","when":"2024-10-19T22:31:49Z","uid_a":"a_0"},{"anon":"no","uid":"lmpga1m6ftd62m","data":"m2gxicmeqxn59h","type":"i_answer_update","when":"2024-10-20T01:48:37Z"},{"anon":"stud","to":"m2go5zb93dh7fx","type":"feedback","when":"2024-10-20T02:00:45Z","cid":"m2gxxyukimq4x3","uid_a":"a_0"},{"anon":"no","uid":"kfoqmke78c463e","to":"m2go5zb93dh7fx","type":"feedback","when":"2024-10-20T05:59:22Z","cid":"m2h6gte2aga4q8"},{"anon":"no","uid":"ln0md59uz9w3kd","to":"m2go5zb93dh7fx","type":"feedback","when":"2024-10-20T06:33:52Z","cid":"m2h7p6n8rlg3nl"}],"bucket_name":"Today","history":[{"anon":"stud","uid_a":"a_0","subject":"Getting Index Out of Bounds Error","created":"2024-10-19T22:31:49Z","content":"I have been getting an index out of bounds error for part 1 for quite some time now and after debugging it seems the UNK index is getting index 14924 and PAD index is 14923. I found that the embedding size for the embedding layer is 14923 so I suspect this is why I&#39;m getting the error? I&#39;m not sure if I can change where UNK index is mapped to to be within range or how I can solve this."},{"anon":"stud","uid_a":"a_0","subject":"Getting Index Out of Bounds Error","created":"2024-10-19T22:30:31Z","content":"I have been getting an index out of bounds error for part 1 for quite some time now and after debugging it seems the UNK index is getting index 14924 and PAD index is 14923. I found that the embedding size for the embedding layer is 14923 so I suspect this is why I&#39;m getting the error? I&#39;m not sure if I can change where UNK index is mapped to to be within range or how I can solve this. "},{"anon":"stud","uid_a":"a_0","subject":"Getting Index Out of Bounds Error","created":"2024-10-19T21:27:03Z","content":"<p>Hello Po-Chun Wo</p>\n<p></p>\n<p>I have been getting an index out of bounds error for part 1 for quite some time now and after debugging it seems the UNK index is getting index 14924 and PAD index is 14923. I found that the embedding size for the embedding layer is 14923 so I suspect this is why I&#39;m getting the error? I&#39;m not sure if I can change where UNK index is mapped to to be within range or how I can solve this. </p>"}],"type":"question","tags":["pa1","student"],"tag_good":[],"unique_views":132,"children":[{"history_size":2,"folders":[],"data":{"embed_links":[]},"created":"2024-10-19T22:28:25Z","bucket_order":3,"tag_endorse":[{"role":"student","name":"CHERYL STANLEY","endorser":{},"admin":false,"photo":null,"id":"m10qfbzbhan2hx","photo_url":null,"published":true,"us":false,"facebook_id":null}],"bucket_name":"Today","history":[{"anon":"no","uid":"lmpga1m6ftd62m","subject":"","created":"2024-10-20T01:48:37Z","content":"<p>I recommend you double-check how you utilize the <code>read_word_embeddings()</code> function in <code>sentiment_data.py</code>:</p>\n<div></div>\n<div>\n<div dir=\"ltr\"><code># Make position 0 a PAD token\nword_indexer.add_and_get_index(&#34;PAD&#34;)\n</code></div>\n<div dir=\"ltr\"><code># Make position 1 the UNK token\nword_indexer.add_and_get_index(&#34;UNK&#34;)</code></div>\n<div dir=\"ltr\"><code></code></div>\n</div>\n<p>The first two indices should be <code>&lt;PAD&gt;</code> and <code>&lt;UNK&gt;</code>. This should help resolve the out-of-bounds error you&#39;re encountering.</p>"},{"anon":"no","uid":"ln0md59uz9w3kd","subject":"","created":"2024-10-19T22:28:25Z","content":"<p>I recommend you double-check how you utilize the <code>read_word_embeddings()</code> function in <code>sentiment_data.py</code>:</p>\n<div></div>\n<div>\n<div dir=\"ltr\"><code># Make position 0 a PAD token\nword_indexer.add_and_get_index(&#34;PAD&#34;)\n</code></div>\n<div dir=\"ltr\"><code># Make position 1 the UNK token\nword_indexer.add_and_get_index(&#34;UNK&#34;)</code></div>\n<div dir=\"ltr\"><code></code></div>\n</div>\n<p>The first two indices should be <code>&lt;PAD&gt;</code> and <code>&lt;UNK&gt;</code>. This should help resolve the out-of-bounds error you&#39;re encountering.</p>"}],"type":"i_answer","tag_endorse_arr":["m10qfbzbhan2hx"],"children":[],"id":"m2gqcwdk65v1l8","config":{"editor":"rte"},"is_tag_endorse":false},{"anon":"no","folders":[],"data":{"embed_links":null},"no_upvotes":0,"subject":"<p>Also, would you mind making this post public instead of private (you can choose to remain anonymous to your classmates)? Others may have similar questions, and it could be helpful for them as well. </p>\n<p></p>\n<p>Please only send us private messages when personal information is shared.</p>\n<p></p>\n<p>Thanks!</p>","created":"2024-10-19T22:28:50Z","bucket_order":3,"bucket_name":"Today","type":"followup","tag_good":[],"uid":"ln0md59uz9w3kd","children":[{"anon":"stud","folders":[],"data":{"embed_links":null},"subject":"Sure!","created":"2024-10-19T22:31:34Z","bucket_order":4,"bucket_name":"Yesterday","type":"feedback","tag_good":[],"uid_a":"a_0","children":[],"tag_good_arr":[],"id":"m2gqgy1on567di","d-bucket":"Yesterday","updated":"2024-10-19T22:31:34Z","config":{"editor":"rte"}},{"anon":"stud","folders":[],"data":{"embed_links":null},"subject":"<p>So I am currently getting -1 after printing out index even though I have set it to &lt;unk&gt; index for case where index = -1. is this why there might be an IndexOutofBounds issue?</p>\n<p></p>\n<p>If I am understanding correctly, the code is defining UNK to be 1, so this shouldn&#39;t be occurring. I am using the existing indexof method to get the unk index so I&#39;m not sure why this issue is occuring. Any help would be greatly appreciated.</p>","created":"2024-10-20T02:00:45Z","bucket_order":3,"bucket_name":"Today","type":"feedback","tag_good":[],"uid_a":"a_0","children":[],"tag_good_arr":[],"id":"m2gxxyukimq4x3","updated":"2024-10-20T02:00:45Z","config":{"editor":"rte"}},{"anon":"no","folders":[],"data":{"embed_links":null},"subject":"Changing the content of the Indexer() class itself may help.","created":"2024-10-20T05:59:22Z","bucket_order":3,"bucket_name":"Today","type":"feedback","tag_good":[],"uid":"kfoqmke78c463e","children":[],"tag_good_arr":[],"id":"m2h6gte2aga4q8","updated":"2024-10-20T06:00:38Z","config":{"editor":"rte"}},{"anon":"no","folders":[],"data":{"embed_links":null},"subject":"@29","created":"2024-10-20T06:33:52Z","bucket_order":3,"bucket_name":"Today","type":"feedback","tag_good":[],"uid":"ln0md59uz9w3kd","children":[],"tag_good_arr":[],"id":"m2h7p6n8rlg3nl","updated":"2024-10-20T06:33:52Z","config":{"editor":"rte"}}],"tag_good_arr":[],"no_answer":1,"id":"m2gqdfsmeup2ch","updated":"2024-10-20T06:33:52Z","config":{"editor":"rte"}}],"tag_good_arr":[],"no_answer":0,"id":"m2go5zb93dh7fx","config":{"editor":"rte","has_emails_sent":1},"status":"active","drafts":{},"request_instructor":0,"request_instructor_me":false,"bookmarked":4,"num_favorites":0,"my_favorite":false,"is_bookmarked":false,"is_tag_good":false,"q_edits":[],"i_edits":[],"s_edits":[],"t":1731990214799,"default_anonymity":"no"},"error":null,"aid":"m3ny96rnrh83lg"}