{"result":{"history_size":1,"folders":["hw2"],"nr":102,"data":{"embed_links":[]},"created":"2024-10-25T01:54:10Z","bucket_order":3,"no_answer_followup":0,"change_log":[{"anon":"stud","data":"m2o2wrhifs47n2","v":"all","type":"create","when":"2024-10-25T01:54:10Z","uid_a":"a_0"},{"anon":"no","uid":"ln0saa4uy359r","data":"m2o8wta9zwe2bt","to":"m2o2wrhbt8l7n1","type":"i_answer","when":"2024-10-25T04:42:10Z"},{"anon":"stud","to":"m2o2wrhbt8l7n1","type":"followup","when":"2024-10-25T17:22:56Z","cid":"m2p035p1vsa2sr","uid_a":"a_0"},{"anon":"no","uid":"ln0saa4uy359r","to":"m2o2wrhbt8l7n1","type":"feedback","when":"2024-10-25T17:32:56Z","cid":"m2p0g0msgy92u9"}],"bucket_name":"Today","history":[{"anon":"stud","uid_a":"a_0","subject":"Question 3 - Homework 2","created":"2024-10-25T01:54:10Z","content":"<p>I&#39;m facing an issue in the question 3 of homework 2 where when following the below mentioned method in homework stub 2 I&#39;m getting the error </p>\n<p>in the screenshot : Could you please suggest an alternative for the same ?</p>\n<p></p>\n<pre>\nXtrain, Xvalid, Xtest = X[:len(X)//2], X[len(X)//2:(3*len(X))//4], X[(3*len(X))//4:]\nytrain, yvalid, ytest = y[:len(X)//2], y[len(X)//2:(3*len(X))//4], y[(3*len(X))//4:]</pre>\n<p></p>\n<p></p>\n<p><img src=\"/redirect/s3?bucket=uploads&amp;prefix=paste%2Flxx2pc0mfhg10o%2F1424d81cbf52d8192be5c0b8efb834f262d035ed279f4744bd89303a5c8c460c%2Fimage.png\" alt=\"image.pngNaN\" width=\"1199\" height=\"562\" /></p>"}],"type":"question","tags":["hw2","student"],"tag_good":[],"unique_views":190,"children":[{"history_size":1,"folders":[],"data":{"embed_links":[]},"created":"2024-10-25T04:42:10Z","bucket_order":3,"tag_endorse":[],"bucket_name":"Today","history":[{"anon":"no","uid":"ln0saa4uy359r","subject":"","created":"2024-10-25T04:42:10Z","content":"<md>The error message indicates that there is only one class in your `ytrain`. However, it's quite unusual to happen. In the stub, before splitting the dataset, we manually set the random seed to avoid such a problem.\n\n```python\nrandom.seed(3)\nrandom.shuffle(dataset)\n```\n\nCould you please check whether there is any additional code to change the original data split pipeline?</md>"}],"type":"i_answer","tag_endorse_arr":[],"children":[],"id":"m2o8wta2xko2bs","config":{"editor":"md"},"is_tag_endorse":false},{"anon":"stud","folders":[],"data":{"embed_links":null},"no_upvotes":0,"subject":"<p>Hi Yupeng,</p>\n<p></p>\n<p>I think I figured out the issue. I had a data frame that I was trying to convert to NumPy when shuffling. Initially, I added the conversion inside the shuffle function itself, which is why the splitting wasn’t working. However, when I first converted it and then used it as a variable in the shuffle function (as shown below), it worked.</p>\n<p></p>\n<p>df_np = df.to_numpy()</p>\n<div><br />\n<div>np.random.seed(3)</div>\n<div>np.random.shuffle(df_np)</div>\n</div>\n<div></div>\n<div>Thanks for your suggestion and help!</div>\n<div></div>\n<div></div>","created":"2024-10-25T17:22:56Z","bucket_order":3,"bucket_name":"Today","type":"followup","tag_good":[],"uid_a":"a_0","children":[{"anon":"no","folders":[],"data":{"embed_links":null},"subject":"<md>Awesome! Glad to hear that!</md>","created":"2024-10-25T17:32:56Z","bucket_order":3,"bucket_name":"Today","type":"feedback","tag_good":[],"uid":"ln0saa4uy359r","children":[],"tag_good_arr":[],"id":"m2p0g0msgy92u9","updated":"2024-10-25T17:32:56Z","config":{"editor":"md"}}],"tag_good_arr":[],"no_answer":0,"id":"m2p035p1vsa2sr","updated":"2024-10-25T17:32:56Z","config":{"editor":"rte"}}],"tag_good_arr":[],"no_answer":0,"id":"m2o2wrhbt8l7n1","config":{"editor":"rte","has_emails_sent":1},"status":"active","drafts":{},"request_instructor":0,"request_instructor_me":false,"bookmarked":3,"num_favorites":0,"my_favorite":false,"is_bookmarked":false,"is_tag_good":false,"q_edits":[],"i_edits":[],"s_edits":[],"t":1731989160037,"default_anonymity":"no"},"error":null,"aid":"m3nxmkwo9e52sd"}