{"result":{"history_size":1,"folders":["assignment1"],"nr":396,"data":{"embed_links":[]},"created":"2024-11-18T04:00:08Z","bucket_order":3,"no_answer_followup":1,"change_log":[{"anon":"stud","data":"m3mhz73ueag5wl","v":"all","type":"create","when":"2024-11-18T04:00:08Z","uid_a":"a_0"},{"anon":"no","uid":"l8ahma4c7ts656","data":"m3n4ry8juzklx","to":"m3mhz73m3kx5wk","type":"i_answer","when":"2024-11-18T14:38:21Z"},{"anon":"stud","uid_a":"a_0","to":"m3mhz73m3kx5wk","type":"followup","when":"2024-11-18T20:16:32Z","cid":"m3nguutkfze5yt"}],"bucket_name":"Today","history":[{"anon":"stud","uid_a":"a_0","subject":"userID not found","created":"2024-11-18T04:00:08Z","content":"For Q1 when I try to run my solution on pairs_Read, it gives me and error saying that one of the userIDs was not found in my userIDs dict. I&#39;m really confused because when I ran it earlier it had no issues and even in a previous iteration of my prediction_Read I can see that the userID was there. I have tried reimporting the data file as well as restarting my kernel and VSCode itself.Â "}],"type":"question","tags":["assignment1","student"],"tag_good":[],"unique_views":196,"children":[{"history_size":1,"folders":[],"data":{"embed_links":[]},"created":"2024-11-18T14:38:21Z","bucket_order":3,"tag_endorse":[],"bucket_name":"Today","history":[{"anon":"no","uid":"l8ahma4c7ts656","subject":"","created":"2024-11-18T14:38:21Z","content":"Print out the userID that was not found and see if it helps"}],"type":"i_answer","tag_endorse_arr":[],"children":[],"id":"m3n4ry8dvq1lw","config":{},"is_tag_endorse":false},{"anon":"stud","folders":[],"data":{"embed_links":null},"no_upvotes":0,"subject":"<p>Its missing around 70 of the IDs. I don&#39;t know what changed between the first time I ran it and the most recent time. I put in a catch statement to predict if a user has read a book based on the books popularity for any user that isn&#39;t found as a work around, but I was never able to pinpoint the source of the issue.</p>\n<p></p>","created":"2024-11-18T20:16:32Z","bucket_order":3,"bucket_name":"Today","type":"followup","tag_good":[],"uid_a":"a_0","children":[],"tag_good_arr":[],"no_answer":1,"id":"m3nguutkfze5yt","updated":"2024-11-18T20:16:32Z","config":{"editor":"rte"}}],"tag_good_arr":[],"no_answer":0,"id":"m3mhz73m3kx5wk","config":{"editor":"rte","has_emails_sent":1},"status":"active","drafts":{},"request_instructor":0,"request_instructor_me":false,"bookmarked":3,"num_favorites":0,"my_favorite":false,"is_bookmarked":false,"is_tag_good":false,"q_edits":[],"i_edits":[],"s_edits":[],"t":1731986721230,"default_anonymity":"no"},"error":null,"aid":"m3nw6b3z2yy720"}